### ISSUE TITLE
Yuri's Revenge version of editor won't load

### ISSUE THREAD

**Issue by daveRobertsDigital** [CnCNet/WorldAlteringEditor#74]
Log from except.txt

```
14.10. 19:01:33.872    Unhandled exception! @ 19:01:33
14.10. 19:01:33.872    Message: Invalid font index: 0
14.10. 19:01:33.880    Stack trace:    at Rampastring.XNAUI.Renderer.GetTextDimensions(String text, Int32 fontIndex)
   at Rampastring.XNAUI.XNAControls.XNALabel.RefreshClientRectangle()
   at Rampastring.XNAUI.XNAControls.XNALabel.set_Text(String value)
   at TSMapEditor.UI.MainMenu.Initialize() in D:\a\TSMapEditor\TSMapEditor\src\TSMapEditor\UI\MainMenu.cs:line 52
   at Rampastring.XNAUI.WindowManager.AddAndInitializeControl(XNAControl control)
   at TSMapEditor.Rendering.GameClass.InitMainMenu() in D:\a\TSMapEditor\TSMapEditor\src\TSMapEditor\Rendering\GameClass.cs:line 139
   at TSMapEditor.Rendering.GameClass.Initialize() in D:\a\TSMapEditor\TSMapEditor\src\TSMapEditor\Rendering\GameClass.cs:line 133
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at TSMapEditor.Program.Main(String[] args) in D:\a\TSMapEditor\TSMapEditor\src\TSMapEditor\Program.cs:line 26
```

**Comment by Rampastring** [comment]
Apparently the release build workflow had a bug where it failed to publish all necessary files for the YR build. I fixed it, so the next release should include a functional build.

However, the editor does not officially support Yuri's Revenge yet. YR support is still work-in-progress and the current YR build is only initial preparation for future YR support. There'll be a separate announcement from when YR support is ready.
